### PR TITLE
Pin shapely to 1.7a3

### PR DESCRIPTION
**Pull request by m-kuhn**
The only difference I could spot between the last working and current failing build...

### CODE REVIEW

**Comment by anitagraser** [comment]
Thank you Matthias, much appreciated!

**Comment by martinfleis** [comment]
Hi @m-kuhn, @anitagraser,

why is there a pin to one specific alpha pre-release of shapely in requirements? That does not seem to be a long-term solution of (assumed) issues and can cause dependency conflicts.

cc https://github.com/pyOpenSci/software-review/issues/18

**Comment by anitagraser** [comment]
Travis started failing even for previously working builds (tested on #62):

Screenshot 2020-01-19 10 48 06

Screenshot 2020-01-19 10 50 36

I hope that the issue will be fixed in the next shapely release.

**Comment by martinfleis** [comment]
Have you reported it to shapely? They seem to be unaware of the issue (https://github.com/Toblerity/Shapely/issues/818#issuecomment-576977788).

Locally all tests pass until `movingpandas/tests/test_trajectory.py::TestTrajectory::test_hvplot_exists`, which kills python.

cc @sgillies

**Comment by anitagraser** [comment]
@martinfleis I hadn't reported the issue yet but I've left a comment on the issue you linked now.

**Comment by martinfleis** [comment]
It seems to be an issue affecting any geo hvplot https://github.com/holoviz/hvplot/issues/409, but it's hard to track down.

**Comment by anitagraser** [comment]
@martinfleis now the pin started to fail https://github.com/anitagraser/movingpandas/issues/75

**Pull request merged**
