### PR TITLE
Issue 249: Fixed typo in mrr_diagonal

### PR DESCRIPTION
**Pull request by snelmes**
Fixed typo in mrr_diagonal as described in issue #249 . Pytest tests ran and all passed.

### CODE REVIEW

**Comment by snelmes** [comment]
Unit test added

**Comment by raybellwaves** [comment]
Nice thanks @snelmes. If you used the environment.yml provided you can run `pre-commit run --all-files` to fix the linting

**Comment by snelmes** [comment]
pre-commit run --all-files run

**Comment by anitagraser** [comment]
Thank you very much, @snelmes

**Pull request merged**
