### PR TITLE
Fix error in RTD configuration

### LINKED ISSUE #145: Broken docs build
Log: https://readthedocs.org/api/v2/build/15140261.txt

It's an upstream issue: https://github.com/sphinx-doc/sphinx/issues/9727

### PR DESCRIPTION
**Pull request by astrojuanlu**
Fix #145, follow-up to #154, should be OK now (sorry for the noise).

### CODE REVIEW

**Comment by astrojuanlu** [comment]
It worked now!

...But not so fast, autodoc is empty:

```
WARNING: autodoc: failed to import module 'movingpandas'; the following exception was raised:
No module named 'pandas'
```

Fixing.

**Comment by astrojuanlu** [comment]
This is now working, including autodoc: https://movingpandas--155.org.readthedocs.build/en/155/trajectory.html

I see that in earlier versions Cartopy was not installed, unsure why. In any case, I got the required system dependencies to get everything working.

**Comment by anitagraser** [comment]
Thanks so much, Juan Luis!

**Comment by astrojuanlu** [comment]
My pleasure! Happy to help, glad it's working now 😄

**Pull request merged**
