### PR TITLE
Run black

### PR DESCRIPTION
**Pull request by anitagraser**
Next step in #143

### CODE REVIEW

**Comment by anitagraser** [comment]
@raybellwaves I really dislike how black reformats the setups in the unit tests. Therefore, I've excluded the tests directory from the black run. This means that linting still fails. Are there ways to selectively tell the linting system to ignore a directory / certain files?

**Comment by raybellwaves** [comment]
> @raybellwaves I really dislike how black reformats the setups in the unit tests. Therefore, I've excluded the tests directory from the black run. This means that linting still fails. Are there ways to selectively tell the linting system to ignore a directory / certain files?

I'm -1 on not applying black to some parts of the repo. It negates tools like pre-commit as well as linting and formatting CI steps. My motivation for #143 is ease of use  of development in IDE's e.g. VSCode as well as standardizing PyData repos to make it easier for geopandas devs to contribute here and vice versa.\

Taken from the website: "Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters."

**Comment by anitagraser** [comment]
Do you have an idea how to keep this a little more readable, i.e. so the method fits on one screen page?

image

**Comment by anitagraser** [comment]
Ok, switched from dicts to lists. That's more readable.

**Comment by anitagraser** [comment]
I think we need to tell flake8 in the linting step to use the black line length of 88 chars.

**Comment by anitagraser** [comment]
Ah here it is: https://github.com/geopandas/geopandas/blob/main/setup.cfg

```
[flake8]
# Black enforces 88 characters line length
max_line_length = 88

ignore =
    E203,  # Space before : (needed for black formatting of slices)
    W503,  # Line break before binary operator (needed for black)
    F821   # TODO: fix F821 issues (see GH #1120) and remove this line
```

**Comment by anitagraser** [comment]
Looks like setup.cfg is being ignored.

**Comment by alexgleith** [comment]
Add it as an argument to the flake command like `--ignore=E1,E23,W503`

**Comment by raybellwaves** [comment]
Made a PR this branch here https://github.com/anitagraser/movingpandas/pull/174

Fixes linting on `trajectory_aggregator.py`

**Pull request merged**
